### ISSUE TITLE
Datasets have "classes = -1" but are used in classification tasks

### ISSUE THREAD

**Issue by amueller** [openml/openml-data#20]
for example:
https://www.openml.org/d/210
https://www.openml.org/d/8

Looks like these are regression datasets (is that documented?)
I'm not sure if it's a good idea to allow these to be run as classification problems. You can, but then the number of classes is not -1, but the number of unique values.

**Comment by joaquinvanschoren** [comment]
Looks solved. Closing this. Will create an overview issue for remaining tasks.
