### ISSUE TITLE
libras_move should have 15 classes, has 0

### ISSUE THREAD

**Issue by amueller** [openml/openml-data#33]
https://www.openml.org/d/299

Maybe we can write some kind of check for this?

**Comment by amueller** [comment]
Is the way to fix these to download the data and upload it again as a different version with the values fixed? Are the number of classes not computed automatically?

**Comment by amueller** [comment]
Other dataset with that issue:
https://www.openml.org/d/294

**Comment by joaquinvanschoren** [comment]
Thanks for reporting! Subsumed by #37
