### ISSUE TITLE
License: Public in dataset description

### ISSUE THREAD

**Issue by Li0ness** [openml/openml-data#53]
Hi,

Please help me to understand what does it mean License: Public in dataset description. What license type is encrypted here?
For example, dataset https://www.openml.org/search?type=data&status=active&id=43939&sort=runs maked as Public

**Comment by joaquinvanschoren** [comment]
It means that there are no known copyright restrictions:
https://creativecommons.org/share-your-work/public-domain/

**Comment by Li0ness** [comment]
Thanks a lot for the answer!
