### ISSUE TITLE
spambase dataset warning with python API

### ISSUE THREAD

**Issue by amueller** [openml/openml-data#60]
Trying to get the "spambase" dataset (which is part of CC-18) I get
```
Could not download file from http://openml1.win.tue.nl/dataset46/dataset_46.pq: Bucket does not exist or is private.
```

**Comment by PGijsbers** [comment]
"spambase" does not seem to give a warning for me, but your warning looks like it would come from the "splice" dataset (id 46). That one did indeed not have a parquet file. I just regenerated it and the warning should no longer be given.

**Comment by amueller** [comment]
hm neither 46 or 44 give me an issue now, so might have been a fluke. thanks for checking!

**Comment by PGijsbers** [comment]
No, as I said I _did_ regenerate the parquet file for dataset 46. It probably was just a name mixup when opening the issue. But thanks for confirming the issue is solved.

**Comment by amueller** [comment]
There is a saying in German, "those who can read have the clear adavantage". Thank you for your help.
